### ISSUE TITLE
README.md is a bit confusing

### ISSUE THREAD

**Issue by goneri** [naparuba/opsbro#1]
Hi Jean,

I don't know what Kunai is and I'm bit confused by the README. For example, what is a service? a node? Is it a tool similar to etcd or Consult?

**Comment by naparuba** [comment]
yes, it's totally different from shinken terms. It's really like Consuls. I'll make it more clear inthe readme.
(resume: check=shinken service, service = do nto exist in shinken :) )

**Comment by naparuba** [comment]
done :)

**Comment by goneri** [comment]
I dropped a little comment to improve the wording :) https://github.com/naparuba/kunai/commit/f0423179e23fa2e962aed9d7c7976c8218f6f7bc

**Comment by naparuba** [comment]
commited, thanks :p

**Comment by goneri** [comment]
my pleasure :)
