### ISSUE TITLE
warning: setlocale: LC_ALL in kunai: line 42

### ISSUE THREAD

**Issue by martinec** [naparuba/opsbro#2]
Starting kunai service:

```
/etc/init.d/kunai start
```

A warning message is showed

```
/etc/init.d/kunai: line 42: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF8): No such file or directory
```

**Comment by martinec** [comment]
Solved using

```
locale-gen en_US.UTF-8
dpkg-reconfigure locales
```
and putting in /etc/default/locale
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
```

**Comment by naparuba** [comment]
Sorry I didn't saw you ticket.
I'm fixing it, in a bung of commit that improve various system managment (all debian, centos, ubuntu and some other various distro).

**Comment by martinec** [comment]
Merci !

**Comment by naparuba** [comment]
(salut, j'ai rajouté beaucoup, beaucoup de choses dernièrement dans kunai mais sans mettre à jour le readme/doc. c'est ma prochaine tâche avec la todo list que je vais passer du fichier texte vers des tickets github ^^ Donc si tu as des questions hésites pas ^^)
