### ISSUE TITLE
Bug à l'installation et manque de documentation

### ISSUE THREAD

**Issue by sbonnegent** [naparuba/opsbro#51]
Il manque, à priori, les pointeurs vers la documentation de configuration.

Après installation, le répertoire **/etc/opsbro** n'existe pas, et on ne trouve pas de lien vers une documentation à ce sujet.

**Comment by naparuba** [comment]
Salut,

Tu as les traces de l'installations? 

Pour la doc oui je suis en train de travailler dessus, j'ai un autre repo où j'avais le site de doc, je vais directement l'intégrer avec les sources.

Pour l'install, tu es sur quelle distro?

Merci :)


Jean

**Comment by naparuba** [comment]
note: je me suis permis de renommer le titre pour qu'il soit plus clair.

**Comment by sbonnegent** [comment]
Je test actuellement sur une Fedora 26. Malheureusement, je n'ai plus le fichier /tmp/opsbro.setup.log.
Y-a-t-il des logs dans un autre fichier ?

**Comment by naparuba** [comment]
Nop. J'ai des tests sur fedora 24 et 25 (test/docker-files).

Je regarde s'il y a une fedora 26 sur docker pour que je puisse rejouer ça :)

**Comment by sbonnegent** [comment]
Par contre, pour info, j'ai lancé plusieurs fois le setup car il me manquait certains paquets nécessaires à l'installation. Cela a peut être joué.

**Comment by naparuba** [comment]
hum l'install fedora a besoin des prerequis en effet, car j'ai pas codé le "driver" du remplaçant de yum (dnf c'est ça?).

Ça a du jouer, je vais voir si j peux rejouer ça.

**Comment by sbonnegent** [comment]
Oui, c'est ça, c'est 'dnf' sur le même modèle que 'yum'.

Dans la série, je test aussi l'installation sur une centos 7 et ça ne passe pas. Je fais une autre issue :)

**Comment by naparuba** [comment]
même modèle mais pas du tout les même lib python en fait, c'est pour ça qu'il est pas intégré "out of the box"

**Comment by naparuba** [comment]
avec les pre-req ça passe sur fedora (en tout cas l'install finie et ça se lance bien)
je pousse le docker file su tu veux rejouer ça

**Comment by naparuba** [comment]
Tu peux retenter avec ça comme modèle pour voir?
https://github.com/naparuba/opsbro/commit/f9b740e845dcce0940366daf42ac15aa3e6fed55

Merci

**Comment by sbonnegent** [comment]
J'ai fait un pull et installé les prérequis. Le "python setup.py install" se passe bien, par contre le fichier '/tmp/opsbro.setup.log' reste vide ainsi que le répertoire '/etc/opsbro'. 

Je peux peut être forcé une désinstallation et réinstaller ?

**Comment by naparuba** [comment]
pour info j'ai codé le backend dnf/fedora, et rajouté pleins de tests sur l'install. S'il y a encore des soucis ou des nouveaux, n'hésites pas à ouvrir un nouveau ticket :)
