### ISSUE TITLE
Installation sur Centos 7

### ISSUE THREAD

**Issue by sbonnegent** [naparuba/opsbro#52]
Sur une Centos 7.4.1708 toute fraiche et à jour, j'ai installé quelques prérequis:

$ yum install leveldb leveldb-devel python-pip

Ensuite l'installation échoue sur le message suivant:

──────────── Checking prerequites (1/3) ────────────────────────────────────────
 * Your system centos (version 7.4.1708) is managed by this installer: √
   - it will be able to use system package manager to install dependencies.
 * checking dependency for leveldb              : MISSING
   - Trying to install the package python-leveldb       from system packages  : (missing in package)
   - cannot install the package from the system. Switching to an installation based on the python pip system (need an internet connection)
Traceback (most recent call last):
  File "setup.py", line 448, in <module>
    cprint('\n'.join(['%s%s' % (_prefix, s) for s in str(exp).splitlines()]), color='grey')
  File "/opt/opsbro/opsbro/misc/termcolor.py", line 130, in cprint
    print((colored(text, color, on_color, attrs)), **kwargs)
  File "/usr/lib64/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)

**Comment by naparuba** [comment]
Hum je pensais les avoir tous catché ce genre d'erreur avec la gestion utf8 forcée. Je regarde et je te propose un autre lancement pour voir.

**Comment by sbonnegent** [comment]
Ah oui, ces erreurs sont pénibles en python2 :)

**Comment by sbonnegent** [comment]
Problème résolu en supprimant la variable d'environnement LANG.

$ echo $LANG
fr_FR.UTF-8
$ unset LANG
$ python setup.py install

Tout est installé (y compris la doc et le répertoire /etc/opsbro).
À priori, cette issue peut être fermée.

**Comment by naparuba** [comment]
Ca m'embète que ça soit pas "out of the box" malgrés le fait qu'on ait le contournement, perso je vais laisser le bug ouvert, après tu peux te déenregistrer du bruit par contre ;)

Je vais me mettre un serveur en fr pour le reproduire et voir comment je peux catcher ça :)

**Comment by naparuba** [comment]
J'ai fixé ça, avec la gestion utf8 sur les backend d'install aussi. J'ai testé ça passe bien sur un fr_FR.UTF8. :)
