### ISSUE TITLE
Les modules devraient pouvoir demander l'installation de leurs dépendances

### ISSUE THREAD

**Issue by jcpassard** [naparuba/opsbro#53]
Il s'agit peut-etre d'un bug contextuel. Le style est fraichement installé : Debian 9.3 et installation opsbro aujourd'hui.

python-numpy manquant, empêchant le daemon de démarrer après activation du module statsd : 

[2017-12-12 21:05:26][DEBUG][mumbly] [MODULE.STATSD]: UDP RCVBUF 425984
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/opsbro-0.4b1-py2.7.egg/opsbro/modulemanager.py", line 75, in prepare
    mod.prepare()
  File "/var/lib/opsbro/global-configuration/packs/statsd/module/module.py", line 72, in prepare
    import numpy as np
ImportError: No module named numpy
[2017-12-12 21:05:26][ERROR][mumbly] : The module <module___global___statsd___/var/lib/opsbro/global-configuration/packs/statsd/module.StatsdModule object at 0x7f511b1fdf90> did fail to prepare: None

Après install de numpy c'est ok, par contre je n'ai pas eu le problème sur une debian 9.2. installation opsbro le 7/12 au cas ou il s'agit d'une nouvelle dépendance.

**Comment by naparuba** [comment]
Hum le daemon installe ses dépendances "daemons" (genre levedb) au setup.py mais pas celui de tous eses modules sinon ça serait juste too much (surtout pour des modules qu'on utilise pas).

Par contre ça serait intéressant que lors de son init ce module détecte que numpy est pas dispo et demande son installation par package (comme les autres dépendances). Je change ça en feature donc :)

**Comment by naparuba** [comment]
Salut,

j'ai rajouté un nouveau mécanisme pour pouvoir faire des installations automatisée: les compliances.

J'ai utilisé ce mécanisme pour régler le soucis de numpy et statsd. Tu peux le voir sur https://github.com/naparuba/opsbro/blob/master/data/global-configuration/packs/statsd/compliance/install-numpy.yml

En résumé:
* le module statsd s'activera désormais non plus sur un booléen enabled dans son parameters.yml mais si on le mets dans un groupe (par défaut statsd-listener cf https://github.com/naparuba/opsbro/blob/master/data/global-configuration/packs/statsd/parameters/parameters.yml)
* si le module trouve numpy, pas de soucis il fait son boulot, sinon il attends 1s et refait le test d'import
* La règle de compliance tourne régulièrement et si elle trouve ce même groupe alors elle s'active et fait son job (ici package-install), qui détecte son "environnement" (ici il n'y en a qu'un, linux, trouvé avec "system_get_os() == 'linux'") et alors il installe ce qu'il faut comme packages (je par du principe que toutes les distributions utilisent le nom python-numpy). Elle l'installe, et alors le module le trouve et démarre.

Il y a un test qui vérifie tout ça:
https://github.com/naparuba/opsbro/blob/master/test/test_feature_statsd_module.sh

Tu peux voir les différentes règle de compliance et leur état (non utile, cassé, fixée, compliante) avec:
  opsbro compliance state
Et l'historique des actions de corrections des règles de compliance avec:
  opsbro compliance history

Pour l'instant le nombre de type de règle de compliance est limitée (en gros droits sur un fichier et package installé), mais ça se rajoute relativement facilement (cf https://github.com/naparuba/opsbro/tree/master/data/global-configuration/packs/core-functions/compliancebackends pour les deux en questions).

N'hésites pas à me dire si c'est clair ou pas dans la manière où on écrit les règles, je suis preneur de retours :)
