### ISSUE TITLE
Grafana Error 403

### ISSUE THREAD

**Issue by jcpassard** [naparuba/opsbro#54]
Apres desactivation et reactivation du module grafana, j'ai maintenant :
[MODULE.GRAFANA]: Cannot connect to grafana datasources: HTTP Error 403: Forbidden

J'ai refait une api-key et supprimé la datasource. La datasource s'est bien recréée.

Par contre après import du dashboard, je n'ai pas l'image correspondante à l'exemple du readme.md.
Je ne connais pas grafana donc je ne sais pas a quoi m'attendre.

![image](https://user-images.githubusercontent.com/1726542/33907273-e4d41bc4-df84-11e7-8663-83cbe505c434.png)

**Comment by naparuba** [comment]
Salut,

le module ne crée pas de dashboard automatiquement (en tout cas pas encore ^^) il ne crée/clean que les datasources (genre un noeud part en leave, il est enlevé).

Il y a bien les "dashboards" dans opsbro mais pour l'instant je ne vois pas comment les envoyer à grafana (ils utilisent des calculs et expressions que ne gèrent pas grafana).


Jean
